basePath: /
definitions:
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.userRegister:
    properties:
      email:
        type: string
      lastName:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для регистрации пользователей
  title: User Registration API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authorization
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "201":
          description: The user has been successfully authorized.
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid Email
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User authorization
      tags:
      - users
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user in the system
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.userRegister'
      produces:
      - application/json
      responses:
        "201":
          description: The user has been successfully registered
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: User already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: New user registration
      tags:
      - users
swagger: "2.0"
